### ISSUE TITLE
清华裴丹团队举办的 KPI 异常检测比赛

### ISSUE THREAD

**Issue by shidi518** [chenryn/aiops-handbook#2]
请问前五名的代码是否开源了呢

**Comment by zr9558** [comment]
> 请问前五名的代码是否开源了呢

您好，这个问题可以去咨询一下主办方~~~
十分感谢。

**Comment by zr9558** [comment]
> 请问前五名的代码是否开源了呢

好像是没有开源的。

**Comment by chenryn** [comment]
嗯，没有开源的。前几名很多都是厂商的团队，比如新华三啊、loglogic啊、还有南京一家什么公司。看他们答辩PPT都看得出来用的是自己公司PPT模板。
