### ISSUE TITLE
基于lstm的日志异常检测工具包

### ISSUE THREAD

**Issue by d0ng1ee** [chenryn/aiops-handbook#3]
完整版中文介绍：[基于lstm的日志异常检测工具包](https://zhuanlan.zhihu.com/p/118507217)

Github Repo: [logdeep](https://github.com/donglee-afar/logdeep)

 欢迎各位star，提issue以及pr！

**前言**
日志异常检测模型从模型角度可以分为机器学习和深度学习两大方向，目前基于机器学习的已经有港中文开源的[loglizer](https://github.com/logpai/loglizer)框架。
鉴于使用rnn为主的深度模型在训练以及预测过程中api与基于机器学习(sklearn)的有较大差别，因此在实践过程中本人针对近两年发布的有关基于rnn的日志异常检测论文进行总结并提炼出了一个工具包[logdeep](https://github.com/donglee-afar/logdeep)，方便其他研究者继续在此基础上进行创新的工作。

**Comment by chenryn** [comment]
add by https://github.com/chenryn/aiops-handbook/commit/ed007785402f6d12538a6307c8b67e40a03680a1
